### ISSUE TITLE
Mongodb Joins -> Optimize LEFT JOIN to $lookup, not just JOIN

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2385] opened 2017-06-22 23:32 UTC

**Comment by nicflores** [comment] 2017-07-18 04:15
@sellout, I'd like to get a little more insight into what exactly needs to be tested in order to determine whether or not this is fixed. I've tried the query you have in the `rightOuterJoin.test` file but I get this:
```
💪 $ select smallZips.city,zips.state from `/mongo/testdata/smallZips` right outer join `/mongo/testdata/zips` on smallZips.`_id` = zips.`_id`
Query time: 3.9s
 city            | state |
-----------------|-------|
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
  unexpected: NA | MA    |
```
The query works, but that's not the expected query result. Can I test anything else?

**Comment by sellout** [comment] 2017-07-18 04:30
@nicflores You could try adding a filter like `where zips.city ~ "CUSH"` which should give you at least one city/state pair (I pulled that example from the expected result) and a bunch of others (you may also want to set `summaryCount = 50` or something in the REPL so it doesn’t truncate the results).

But, since you can see the test passes, you just want to verify that the test generates the desired plan, which you can do either by just using `explain` (with `debug = 2`) at the REPL, or by running `it/testOnly *StreamingQueryRegression* -- ex "rightOuterJoin"` after uncommenting line 223 in QueryRegressionTest.scala (which prints the phase results for any test that’s run).

**Comment by nicflores** [comment] 2017-07-18 14:03
@sellout, by "plan" do you mean the Logical Plan? Also how will I know it's the desired plan?

**Comment by alissapajer** [comment] 2017-07-18 14:34
@nicflores so in this case when @sellout said "plan" what I believe was meant is the specific query plan that mongo generates. 

This ticket is to make a change in the mongo query planner to use `$lookup` for left joins. So, you'd know it's the desired plan if the resulting query plan has `$lookup` in it where you'd expect. So yeah, this is manual inspection of the debug output in the REPL. The mongo query plan will be the last thing printed in the REPL when you use `debug=2`.

You can see lots of examples of mongo plans in the mongo `PlannerSpec` as well. And when this issue is fixed you can add a new test there for left join, verifying that `$lookup` is in the correct place in the plan.

Also, the results you posted from the REPL above do look correct to me. This query _should_ be producing correct results on the new mongo branch already, since the integration test is passing. Your goal is to change the underlying mongo plan to something more optimal.

As a side note, this is also probably a good query to use to learn about all of the phase results, which is all the SQL, LogicalPlan, and QScript that gets printed when you do `debug=2`. So you can look at those print outs just to get a sense of how the query is processed. That's not directly relevant to this ticket though.

**Comment by alissapajer** [comment] 2017-07-18 16:36
@nicflores so I put a println within [this `case`](https://github.com/sellout/quasar/commit/2bdfdc5f6ac34b7c1770e3a9c915395527f85c04#diff-2a598731f642bc5c7bc5913d05ee2154R186) and it's not being hit. Query I used is
```sql
select cars.name as n1, cars2.name as n2 from cars2 left outer join cars on cars.`_id` = cars2.`_id`
```
So it seems that that `$lookup` optimization in that commit is not being hit. So the next steps would be to figure out why not and if we should actually be hitting it for this query.

**Comment by nicflores** [comment] 2017-07-18 16:54
Ok, thanks for confirming, @alissapajer. Good to know we are observing similar behavior. I'll start tracing through `JoinHandler` and to determine why we aren't falling into those case statements.

**Comment by alissapajer** [comment] 2017-07-18 18:51
This was in theory fixed in https://github.com/sellout/quasar/commit/2bdfdc5f6ac34b7c1770e3a9c915395527f85c04#diff-2a598731f642bc5c7bc5913d05ee2154R186 but since we have evidence that it might not have actually been fixed, I have not applied the "status: Fixed in New Mongo" label.

**Comment by nicflores** [comment] 2017-07-19 04:45
@sellout and I traced through `JoinHandler` today and it turns out we aren't hitting either of these cases:
```
case (JoinType.LeftOuter, JoinSource(src, List(key)), IsLookupFrom(coll, field))
case (JoinType.RightOuter, IsLookupFrom(coll, field), JoinSource(src, List(key)))
``` 
in the definition of `JoinHandler.pipeline`. When `MongoDbPlanner.plan`, `pipeline` returns `None` and we `fallback` to `mapReduce`.

It appears that `JoinHandler.pipeline` doesn't match either of the two cases above due to `IsLookupFrom` incorrectly matching on:
```
case JoinSource(
  Fix(CollectionBuilderF(Fix(ev0($ReadF(coll))), Root(), None)),
  List(HasThat($var(DocVar(_, Some(field)))))) => 
(coll, field).some
```
instead its `JoinSource` has this shape:
```
JoinSource(Fix(ShapePreservingBuilderF(Fix(ExprBuilderF(Fix(CollectionBuilderF(Fix(Coproduct...
```

I'll talk to @alissapajer about next steps.

**Comment by alissapajer** [comment] 2017-07-19 19:52
So, in `IsLookupFrom` we're looking to match on a projection of a single field from a raw read, according to the scaladoc. @nicflores do you have a printout of the entire `JoinSource` we are actually getting? I'm curious to see how much it differs from this description.

**Comment by nicflores** [comment] 2017-07-19 19:55
I do, here it is:
```
JoinSource(Fix(ShapePreservingBuilderF(Fix(ExprBuilderF(Fix(CollectionBuilderF(Fix(Coproduct(\/-($ReadF(Collection(DatabaseName(local),CollectionName(smallZips)))))),Root(),None)),This([_._id, _]))),List(Both(_[1],Fix(Coproduct(-\/($arrayElemAtF(Fix(Coproduct(\/-(Coproduct(\/-($varF(DocVar(Name(ROOT),None))))))),Fix(Coproduct(\/-(Coproduct(\/-($literalF(Int32(1)))))))))))), Both(true,Fix(Coproduct(\/-(Coproduct(\/-($literalF(Bool(true))))))))),<function1>)),List(This(_[1]._id)))
```

**Comment by alissapajer** [comment] 2017-09-06 20:35
This was closed automatically in a commit reference when we merged `next-major`, but this wasn't actually fixed in that commit.

**Closed** 2021-07-12 21:39 UTC
