### ISSUE TITLE
Download produces a CSV with scientific notation

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#2160] opened 2017-05-04 22:42 UTC
given this dataset:

```
{ "_id" : ObjectId("590b99745c4c8f7cc2415267"), "note" : "string 123456789012345", "value" : "123456789012345" }
{ "_id" : ObjectId("590b99895c4c8f7cc2415268"), "note" : "number 123456789012345", "value" : 123456789012345 }
{ "_id" : ObjectId("590b999a5c4c8f7cc2415269"), "note" : "number 1234567890", "value" : 1234567890 }
{ "_id" : ObjectId("590b99a45c4c8f7cc241526a"), "note" : "string 1234567890", "value" : "1234567890" }
{ "_id" : ObjectId("590b9b455c4c8f7cc241526b"), "note" : "string 12345678901", "value" : "12345678901" }
{ "_id" : ObjectId("590b9b495c4c8f7cc241526c"), "note" : "string 123456789012", "value" : "123456789012" }
{ "_id" : ObjectId("590b9b4c5c4c8f7cc241526d"), "note" : "string 1234567890123", "value" : "1234567890123" }
{ "_id" : ObjectId("590b9b9d5c4c8f7cc241526e"), "note" : "number 12345678901", "value" : 12345678901 }
```

A download card produces the following CSV:

```
note,value
string 123456789012345,123456789012345
number 123456789012345,123456789012345
number 1234567890,1.23456789E+9
string 1234567890,1234567890
string 12345678901,12345678901
string 123456789012,123456789012
string 1234567890123,1234567890123
number 12345678901,12345678901
```

Not sure what's going on with that third entry. The only unique thing about it, to my knowledge, is that it's the shortest integer in the data set. One would think the the longer integers would lend themselves to this type of notation though.

Originally filed as SlamData Issue [1745](https://github.com/slamdata/slamdata/issues/1745)

**Comment by zeeiyerWork** [comment] 2017-05-12 18:13
Assigning this to @sellout since the symptoms point to mongo connector, although the cause maybe unrelated to symptom (if so, he should reassign as appropriate)

**Comment by sellout** [comment] 2017-05-14 01:35
@damonLL How are you inserting this data?

If you’re using the Quasar uploader (which distinguishes ints from floats), this _does_ look like a Mongo connector bug.

But if you’re using some other mechanism, you have to remember that we’re dealing with JSON here. `"value" : 1234567890` inserts a floating-point number into the collection, so we get a floating-point number back, and (I think) the Argonaut JSON serializer (not-Mongo-specific) spits it out in scientific notation (which is totally valid JSON).

The more confusing thing to me is that _larger_ numbers aren’t getting the same treatment. They should also be floating-point, but I’m not sure why they’re being serialized differently.

**Comment by zeeiyerWork** [comment] 2017-07-11 17:39
@nicflores -> please get with @damonLL if there are any outstanding questions on this. Thanks

**Closed** 2021-07-12 21:41 UTC
