### ISSUE TITLE
`IfUndefined` not catching "empty"/un-flattenable flattens

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2960] opened 2017-10-20 13:45 UTC
Query:
``` sql
SELECT 
    t0.b[*] ?? t0.b
FROM 
    `/mimir/flattenable` as t0 
```

Input:
``` json
{ "a": 1, "b": [true, true, true] }
{ "a": 2, "b": [false, false] }
{ "a": 3, "b": "string" }
{ "a": 4, "b": null }
```

Actual output:
``` json
true
true
true
false
false
```

Expected:
``` json
true
true
true
false
false
"string"
null
```

**Comment by alissapajer** [comment] 2017-10-25 18:09
<details>
  <summary>logical plan</summary>

```
Rewritten Joins:
Let('__tmp0)
├─ Let('__tmp1)
│  ├─ Read(/mongodb34/test/flattenable.json)
│  ╰─ Typecheck(Obj(Map[], Some(Top)))
│     ├─ Free('__tmp1)
│     ├─ Free('__tmp1)
│     ╰─ Constant(NA)
╰─ Invoke(Take)
   ├─ Invoke(Squash)
   │  ╰─ Invoke(IfUndefined)
   │     ├─ Invoke(FlattenArray)
   │     │  ╰─ Let('__tmp2)
   │     │     ├─ ObjectProject(Free('__tmp0){"b"})
   │     │     ╰─ Typecheck(FlexArr(0, None, Top))
   │     │        ├─ Free('__tmp2)
   │     │        ├─ Free('__tmp2)
   │     │        ╰─ Constant(Arr(List(NA)))
   │     ╰─ ObjectProject(Free('__tmp0){"b"})
   ╰─ Constant(Int(11))
```
</details>

The logical plan is correct, so this is a different issue from #2958. Something is going wrong during qscript compilation, or a connector is mis-evaluating.

**Comment by alissapajer** [comment] 2017-10-25 19:45
The qscript is also correct. `IfUndefined` is not working for mongo. The unit tests are disabled for `IfUndefined`, for example https://github.com/quasar-analytics/quasar/blob/master/mongoIt/src/test/scala/quasar/physical/mongodb/JsStdLibSpec.scala#L62

**Comment by zeeiyerWork** [comment] 2017-10-25 19:47
Based on that assigning this to @jsantos17

**Comment by garyb** [comment] 2017-10-25 19:56
@alissapajer the behaviour I described happens on Mimir as well as Mongo, so maybe there are two issues?

**Comment by alissapajer** [comment] 2017-10-25 20:18
Confirmed the same behavior against mimir, run in SlamData.

**Comment by djspiewak** [comment] 2017-10-30 21:52
I would guess that the issue here is the fact that the `LeftShift` eats the undefineds which stem from the `Guard` that immediately precedes it.  This is actually quite difficult for connectors to piece together, since it requires maintaining holes in the intermediate datasets which arise from `LeftShift`.  It might be possible to get mimir to do this, though I doubt I can do so reliably.  I'm not sure about mongo.

**Comment by djspiewak** [comment] 2017-10-30 21:53
@zeeiyerWork Why is this a ☠️?  This is related to the structure editor, which didn't exist at all before 5.0.  It's not a regression, and nobody has bought it yet.

**Comment by garyb** [comment] 2017-10-30 21:55
Yeah, I don't think it's even a regression within the 4.2.6 -> 5.0 period - my earlier attempts to do flattening used to behave even worse than it does now, so I don't think it got this far before.

**Comment by zeeiyerWork** [comment] 2017-10-30 22:05
The structure editor was part of the promised business deliverable in 5.0.0.

It is a feature being relied on and to be used at Consova (milestone customer in the sales pipeline wrt our pivot to solutions - in this case healthcare). Hobbled versions of structure editor do not seem acceptable to Product as per the conversation at https://github.com/slamdata/slamdata/issues/2386 where even the suggestion to execute 1-edit at a time was deemed as too restrictive.

Further it seems correctness related - Hence the ☠️.   

Also, high level deliverables that were promised to the business in 5.0.0 (earlier called 4.3.0) - has always been available here  @ https://docs.google.com/presentation/d/1rH1scFJTGV2YPL40WxAj2HbS1gl03E6GxL_FJ6PFz6U/edit#slide=id.g24666aeab3_0_4 + been reviewed in team settings a few times.

**Comment by djspiewak** [comment] 2017-10-30 22:14
@zeeiyerWork Does Consova require structure editor to work on *heterogeneous* data *at the pivot points*? Because this issue is confined to exactly that.  Is that hobbling?  I dunno, maybe.  It's certainly functional for any homogeneous dataset, or any dataset where the heterogeneity is not being pivoted by the structure editor.

Strictly-speaking, this isn't a correctness issue since `??` must be understood to not capture all undefineds from its lexical closure.  I can fabricate several other queries which will exhibit a similar issue.  Yes, this *should* work, but it's actually extremely complicated to do and probably requires changes to qscript.

Will the business die if we don't deliver this in 5.0?  (note the caveats on *exactly* where this is an issue)  If not, then the skull isn't merited IMO.

**Comment by djspiewak** [comment] 2017-10-30 22:21
Just to document some conceptualization here…

This can be fixed by pushing the `??` within the `LeftShift`, applying it to the `Guard` and wrapping the right-hand side in an array construction (or object construction, in the case of `{*}`).  This doesn't seem like something @jsantos17 can fix by himself, and unfortunately due to SQL² limitations, it's also not something @garyb can do explicitly.

**Comment by zeeiyerWork** [comment] 2017-10-30 22:31
Sure, IMO if @djspiewak  and @garyb are agreed that this is an edge case confined to heterogenous data at pivot points, no issue dropping the must-fix label (so either of you can feel free to drop the skull) -> we can try to optimistically fix for 5.0.0 or postpone. I am not sure, we are able to answer the question of whether this exact edge case might show up at a prospect deployment.

**Comment by zeeiyerWork** [comment] 2017-10-30 22:59
@djspiewak -> Thanks for initiating the discussion on the rationale behind the prioritization. Please do so in any other case as well so we can ensure multiple POVs are accounted for.

**Comment by zeeiyerWork** [comment] 2017-11-15 21:41
de-prioritizing given that we expect this to be more of an edge-case.

**Comment by zeeiyerWork** [comment] 2017-11-21 21:48
Assigned to @rabbitonweb - since he feels he may have fixed this via work on https://github.com/quasar-analytics/quasar/issues/2958

**Comment by rintcius** [comment] 2017-12-07 13:43
This is not fixed yet. Added IT to track in #3249

**Comment by djspiewak** [comment] 2017-12-07 23:07
Yeah this is a big one (in terms of effort).  I don't have any *good* ideas of how to address this in general yet.

**Closed** 2021-07-12 21:20 UTC
